### ISSUE TITLE
Fail to run the shinjuku.py for a "IsADirectoryError"

### ISSUE THREAD

**Issue by xiunianjun** [google/ghost-userspace#39]
### OS
ghOSt kernel, a VMware Workstation machine
### file directory level
`/home/xiunian/ghost/ghost-userspace/experiments/scripts/shinjuku.py`

## My problem
Fail to run shinjuku.py for this reason :
```
xiunian@xiunian-virtual-machine:~/ghost/ghost-userspace$ sudo python experiments/scripts/shinjuku.py ghost
Running ghOSt experiments...
mount: /dev/cgroup/cpu: cgroup already mounted on /dev/cgroup/cpu.
mount: /dev/cgroup/memory: cgroup already mounted on /dev/cgroup/cpu.
Traceback (most recent call last):
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/shinjuku.py", line 84, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/shinjuku.py", line 80, in main
    RunGhost()
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/shinjuku.py", line 58, in RunGhost
    Run(e)
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/run.py", line 515, in Run
    SetUp(experiment.binaries)
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/setup.py", line 150, in SetUp
    CopyBinaries(binaries)
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/setup.py", line 129, in CopyBinaries
    tmp = UnzipPar()
  File "/home/xiunian/ghost/ghost-userspace/experiments/scripts/setup.py", line 114, in UnzipPar
    with zipfile.ZipFile(GetPar(), "r") as zf:
  File "/usr/lib/python3.10/zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
IsADirectoryError: [Errno 21] Is a directory: '/home/xiunian/ghost'
```
Could you tell me how to resolve this problem? Thanks.

**Comment by jackhumphries** [comment]
You should run the experiment with `bazel-bin/experiments/scripts/shinjuku.par ghost`. Please let me know if this resolves the issue.

**Comment by xiunianjun** [comment]
> 

It's OK now. Thank you very much!!
