### ISSUE TITLE
Error reproduce experiments

### ISSUE THREAD

**Issue by handar423** [google/ghost-userspace#5]
Hello, 

I am not sure if I should reproduce experiments by this command, I just want to run some tests in ghost paper, so I tried this:

➜  scripts git:(main) ✗ bazel run centralized_queuing cfs  
INFO: Analyzed target //experiments/scripts:centralized_queuing (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //experiments/scripts:centralized_queuing up-to-date:
  bazel-bin/experiments/scripts/centralized_queuing
INFO: Elapsed time: 0.588s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Running CFS experiments...
mount: /dev/cgroup/cpu: cgroup already mounted on /sys/fs/cgroup/systemd.
mount: /dev/cgroup/memory: cgroup already mounted on /sys/fs/cgroup/systemd.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/centralized_queuing.py", line 94, in <module>
    app.run(main)
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/my_deps/pypi__absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/my_deps/pypi__absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/centralized_queuing.py", line 86, in main
    RunCfs()
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/centralized_queuing.py", line 50, in RunCfs
    Run(e)
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/run.py", line 523, in Run
    SetUp(experiment.binaries)
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/setup.py", line 158, in SetUp
    CopyBinaries(binaries)
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/setup.py", line 137, in CopyBinaries
    tmp = UnzipPar()
  File "/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles/com_google_ghost/experiments/scripts/setup.py", line 122, in UnzipPar
    with zipfile.ZipFile(GetPar(), "r") as zf:
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
IsADirectoryError: [Errno 21] Is a directory: '/root/.cache/bazel/_bazel_root/7433de7b30d6d58a288c26dfb16d43d1/execroot/com_google_ghost/bazel-out/k8-fastbuild/bin/experiments/scripts/centralized_queuing.runfiles'

Could you please tell me how to fix it?

**Comment by handar423** [comment]
same error occurs for other tests in scripts dir

**Comment by jackhumphries** [comment]
Hi,

Does this also happen when you run the par files directly from the project root? Here is an example:

```
./bazel-bin/experiments/scripts/centralized_queuing.par
```

Jack

**Comment by jackhumphries** [comment]
Closing this. Feel free to reopen if you are still having this issue.

**Comment by handar423** [comment]
Thank you very much for your help, I found another way to solve it.
